#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  methods:
    - GET
  controller: App\Controller\Concurso\ListarConcursos::handle

formulario-concurso:
  path: /formulario-concurso
  methods:
    - GET
  controller: App\Controller\Concurso\FormularioCriarConcurso::handle

novo-concurso:
  path: /novo-concurso
  methods:
    - POST
  controller: App\Controller\Concurso\PersistirConcurso::handle

concurso-por-id:
  path: /concursos/{id}
  methods:
    - GET
  controller: App\Controller\Concurso\ListarConcursoPorId::handle

novo-sorteio-oficial:
  path: /atualizar-sorteio-oficial
  methods:
    - GET
  controller: App\Controller\Concurso\PersistirSorteioOficial::handle