#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  methods:
    - GET
  controller: App\Controller\Concurso\ListarConcursos::handle

formulario-concurso:
  path: /admin/formulario-concurso
  methods:
    - GET
  controller: App\Controller\Concurso\FormularioCriarConcurso::handle

novo-concurso:
  path: /novo-concurso
  methods:
    - POST
  controller: App\Controller\Concurso\PersistirConcurso::handle

concurso-por-id:
  path: /concursos/{id}
  methods:
    - GET
  controller: App\Controller\Concurso\ListarConcursoPorId::handle

formulario-adicionar-cartela:
  path: /formulario-adicionar-cartela/{id}
  methods:
    - GET
  controller: App\Controller\Concurso\FormularioAdicionarCartela::handle

persistir-cartela:
  path: /persistir-cartela/{id}
  methods:
    - POST
  controller: App\Controller\Concurso\PersistirCartela::handle

novo-sorteio-oficial:
  path: /atualizar-sorteio-oficial
  methods:
    - GET
  controller: App\Controller\Concurso\PersistirSorteioOficial::handle

iniciar-concursos:
  path: /iniciar-concursos
  methods:
    - GET
  controller: App\Controller\Concurso\IniciarConcursoAberto::handle