home:
  path: /
  methods:
    - GET
  controller: App\Controller\Concurso\ListarConcursos::handle

concurso-por-id:
  path: /concursos/{id}
  methods:
    - GET
  controller: App\Controller\Concurso\AcompanhamentoConcurso::handle

formulario-adicionar-cartela:
  path: /formulario-adicionar-cartela/{id}
  methods:
    - GET
  controller: App\Controller\Concurso\FormularioAdicionarCartela::handle

persistir-cartela:
  path: /persistir-cartela/{id}
  methods:
    - POST
  controller: App\Controller\Concurso\AdicionarCartelaAoConcurso::handle

formulario-concurso:
  path: /admin/formulario-concurso
  methods:
    - GET
  controller: App\Controller\Admin\FormularioCriarConcurso::handle

novo-concurso:
  path: /admin/novo-concurso
  methods:
    - POST
  controller: App\Controller\Admin\PersistirConcurso::handle

novo-sorteio-oficial:
  path: /admin/atualizar-sorteio-oficial
  methods:
    - GET
  controller: App\Controller\Admin\PersistirSorteioOficial::handle

iniciar-concursos:
  path: /admin/iniciar-concursos
  methods:
    - GET
  controller: App\Controller\Admin\IniciarConcursoAberto::handle

pagar-cartela:
  path: /admin/pagar-cartela/{id}
  methods:
    - GET
  controller: App\Controller\Admin\PagarCartela::handle

app_login:
  path: /admin/login
  methods:
    - GET
    - POST
  controller: App\Controller\Login\SecurityController::login

app_logout:
  path: /admin/logout
  methods:
    - GET
  controller: App\Controller\Login\SecurityController::logout